name: Notifier
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Notifier
        env:
          API_KEY: ${{secrets.API_KEY}}
          API_SECRET: ${{secrets.API_SECRET}}
          FROM_EMAIL: ${{secrets.FROM_EMAIL}}
          TO_EMAIL: ${{secrets.TO_EMAIL}}
          SENDER_NAME: ${{secrets.SENDER_NAME}}
          RECIEVER_NAME: ${{secrets.RECIEVER_NAME}}
          EVENTS: ${{secrets.EVENTS}}
        run: python src/event_notifier.py
